# Bootloader selection
BOOTLOADER = caterina
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
# VIA_ENABLE = yes
